### ISSUE TITLE
Can't Update atom-bugs and atom-bugs-chrome

### ISSUE THREAD

**Issue by AskYous** [willyelm/xatom-debug#15]
Hello,

I'm trying to update my packages but every time I do, the update button appears again, even after restarting atom. It's like it can't update:

![image](https://cloud.githubusercontent.com/assets/791996/25095252/c17e62a2-234f-11e7-88fe-a5f05006a5d2.png)

**Comment by willyelm** [comment]
Hi @AskYous, I renamed the packages probably that is the issue, please try by uninstall and install it again from atom.

**Comment by AskYous** [comment]
Thanks. It works!
