### ISSUE TITLE
Unable to start the debugger.

### ISSUE THREAD

**Issue by xariaD** [willyelm/xatom-debug#16]
Could you please add samples of settings file for both nodejs and chrome plugins

**Comment by dhruvr** [comment]
Its simple like this @xariaD 

![hle](https://cloud.githubusercontent.com/assets/11910246/26779247/5261a6d4-4a02-11e7-9032-ba531084f9e7.png)

**Comment by bodhiprice** [comment]
It really would be great to have some info on the config. The screenshot shared above is appreciated, but I don't see those options anywhere. Any further tips or advice will be much appreciated.

**Comment by Redsandro** [comment]
~~@dhruvr Where can you find those options?~~

It's the 'node.js' button in the debug toolbar that shows up after restarting Atom.

**Comment by jrvansuita** [comment]
The node.js button doesn't appears for me.

![image](https://user-images.githubusercontent.com/12175215/48972831-fcbea000-f019-11e8-9328-055c5e48716d.png)

![image](https://user-images.githubusercontent.com/12175215/48972838-152eba80-f01a-11e8-8e3b-a9513196ac1d.png)
