### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by yamsellem** [willyelm/xatom-debug#2]
Hi,

So here's the [issue #18](https://github.com/willyelm/atom-bugs/issues/18)'s feedback (_old repository issue_):

* Inspecting variable words on mouse enter is working perfectly

* Hiding / Showing `atom bugs` with crtl+shift+D works great, though it could also be nice to have this shortcut available through the menu `Packages > Atom Bugs > Toggle`

* The current line highlight is not yet what I was expected (_I may have not been crystal clear about it, sorry_). The breakpoint line is highlighted on enter, yes, but it is not moving to the current line on each step over / into / out, as it does in Chrome (_displaying the current debugged like is very useful_)

Other considerations:

* I would love to be able to move things around (_I don't care if its the default display, though_), a large `console` at the bottom of the screen, `watch`, `call stack`, `scope` and `break points` to the right, plus, the start / stop buttons within this panel, at the bottom of it (_displaying it at the top of Atom moves the tabs down and I love tabs to be at the top of everything_). Something like this:

![bottom debugging](https://cloud.githubusercontent.com/assets/606754/24615202/f83c30c0-188d-11e7-9457-3ff923c1bb78.png)

* With this display, it would be great if the `watch`, `call stack`, `scope` and `break points` have little arrows to toggle one or several of them, like in Chrome

![chrome](https://cloud.githubusercontent.com/assets/606754/24614727/6c8fe572-188c-11e7-83fd-d718dc6cfa97.png) 

Errors I encountered:

* `console.log(1, 2, 3)` is printed on 3 lines

* I was forced to move to from node 4.x to 6.x to make things work, may you consider supporting node 4.x?

* On starting, it's necessary to click on `Resume` a first time for the server to really start — even if there ain't any breakpoint on server root. May you consider removing that need?

* The remote debugging says `Error: Parse Error`

Like the last time, :champagne:, this tool you're creating is a missing must have for any JavaScript developer. Thanks so much.

**Comment by willyelm** [comment]
Hi , @yamsellem Thank you the feedback you helping me a lot to improve this package. I'll add those updates this week.

**Comment by yamsellem** [comment]
Hello @willyelm, I'm happy to modestly contribute, you're doing something so great! I'll keep looking, and keep giving you some feedback ;-). It's awesome to get your feedback so quickly, as well!

I wish I could code with you, but I'm kinda busy at the moment. I'm also dreaming of a good mocha / ava atom integration, but it's another story.

**Comment by willyelm** [comment]
Some fixes I have take care of so far in the latest version:

- [x] Remote debugging connection fixed.
- [x] Highlight current frame line.
- [x] Only pause on step move and or breakpoint hint.
- [x] Add menus and context menus to toggle, run and stop debugger
- [x] Console prints objects and multiple items on a single line
