### ISSUE TITLE
Debug nodejs ES6?

### ISSUE THREAD

**Issue by zon999** [willyelm/xatom-debug#21]
Hi all,
I wanna debug nodejs es6 project and i used 'import'. Then i got error 

> Unexpected token import 

I try config arguments 

>  --exec babel-node --presets es2015,stage-2

But it still not working. Could you tell me how do i have to config?
Thanks!

**Comment by willyelm** [comment]
How are you building the application do you have the compiled files with source maps available? our you are using register?

**Comment by zon999** [comment]
@willyelm 
Thank you for your reply, i try re-config then it's working fine. 
Maybe i miss some configs :)

**Comment by chrisvoo** [comment]
@zonorion what did you do to make it work? I'm using it inside a react app, which I usually start with `"start": "npm run build-css && run-p -ncr watch-css start-js"`.
thanks
