### ISSUE TITLE
Node inspector process hangs after debug has been stopped

### ISSUE THREAD

**Issue by pablodenadai** [willyelm/xatom-debug#7]
See gif:

![atom bug](https://cloud.githubusercontent.com/assets/3250667/24934883/7d9eed1c-1f72-11e7-84ed-cc1197cec88e.gif)

Windows
Atom v1.15.0
Node v6.10.0

**Comment by willyelm** [comment]
I'll take a look, you are connecting using `remote` right?

**Comment by pablodenadai** [comment]
Nope, it's local (as far as I know). See config below:

Let me know if you need more info.

![image](https://cloud.githubusercontent.com/assets/3250667/24935162/512db7de-1f74-11e7-9222-c5b05eeba3b2.png)

**Comment by willyelm** [comment]
Tested on last version. seems to be killing the process now. please let me know.

**Comment by pablodenadai** [comment]
I've updated the package and restarted Atom. Now I'm experiencing the same problem as https://github.com/atom-bugs/atom-bugs/issues/8#issuecomment-294244802

**Comment by willyelm** [comment]
I will close this since has been fixed already in previous version. Please reopen if any issue.
