### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by AskYous** [willyelm/xatom-debug#8]
Hi,

Congratulations on creating what seems to be a good JS debugging tool based on what I'm seeing so far. I downloaded it and tried it in Atom in Windows. I open my node `app.js` file, clicked the play icon, and I see the `Node.js: Running process` tab loading forever:

![image](https://cloud.githubusercontent.com/assets/791996/25027356/de0be9d6-2060-11e7-8b4d-442b4ab52fa5.png)

When I click 'Node.js' to see the Node settings, I notice the Binary path is set to a folder that's not on Windows `/usr/...`. I changed it to `C:\Program Files\nodejs` (which has node.exe) but it still failed.

I know you don't have documentation yet but can you at least tell me how do I start on Windows? Is this a bug or am I missing something? 

And I am very thankful for what you have made. I hope it advances! Thanks!

**Comment by pablodenadai** [comment]
Try `"C:\Program Files\nodejs\node.exe"` (with double quotes as you have a space in the path)

**Comment by AskYous** [comment]
@pablodenadai,

I tried `"C:\Program Files\nodejs"` and `"C:\Program%20Files\nodejs"` and still it didn't change anything. Still stuck loading :(.

**Comment by willyelm** [comment]
@AskYous you need to point to the .exe file

**Comment by AskYous** [comment]
Aaah ok. It's starting to work. But now it gives a different error. Node.exe is launched. I see the terminal window open. But it opens for like .1 seconds and goes away. Then I see this:

![image](https://cloud.githubusercontent.com/assets/791996/25047813/e7053eba-20ed-11e7-8dfa-8e02970d5cd9.png)

**Comment by willyelm** [comment]
which node version do you have?

**Comment by AskYous** [comment]
I have version **6.10.1**.

**Comment by pablodenadai** [comment]
@AskYous Can you send a screenshot of your config modal/dialog window?

**Comment by AskYous** [comment]
Sure. I can go on Gitter if you wish too.

![image](https://cloud.githubusercontent.com/assets/791996/25055684/29c1b73a-2119-11e7-8085-81efbdcabced.png)

**Comment by pablodenadai** [comment]
Do you have your entry/main file (eg `index.js`) selected when you start the debugger? (as you have selected Run Type = Current File)

**Comment by AskYous** [comment]
Yes. I had app.js selected, which is my main file:

![image](https://cloud.githubusercontent.com/assets/791996/25057248/ec985e36-2122-11e7-9e0a-8665df70d6f1.png)

**Comment by pablodenadai** [comment]
@AskYous I'm having the same problem now that I've updated the package.

**Comment by AskYous** [comment]
Some more information:

I created 1 app.js file that simply has 1 line of code: `console.log('hey')`. I got the same error as above:

![image](https://cloud.githubusercontent.com/assets/791996/25057355/ea515e6a-2123-11e7-9c5e-dba97204fb71.png)

I'm also running the [beta version of Atom](https://atom.io/beta).

**Comment by AskYous** [comment]
@pablodenadai Are you running the beta version of Atom? You can tell if the Atom icon is yellow like in my screenshots.

**Comment by pablodenadai** [comment]
@AskYous Nope, not the beta version. I'm running `v1.16.0` instead.

**Comment by willyelm** [comment]
I've been testing on windows and got it working, please let me know if you still got issues.

![windows-test](https://cloud.githubusercontent.com/assets/1202219/25059737/e42ec730-2159-11e7-882e-e6d535c716ff.gif)

**Comment by pablodenadai** [comment]
I've killed all Node processes + updated the package + restarted Atom. Still the same error.

The label where it should read "Node.js: running node" reads "Node.js: Unable to find page with socket" instead. 

Is there a place where I can see the logs?

**Comment by AskYous** [comment]
@willyelm are you using Node v6.10.1?

**Comment by willyelm** [comment]
my mistake, please update should be working now.

**Comment by AskYous** [comment]
Thanks @willyelm! It's starting to work now. But it looks like it doesn't like that I have a space in my name (my name is Yousef Shanawany):

![image](https://cloud.githubusercontent.com/assets/791996/25061223/2469d432-2166-11e7-98e5-b1748cabfce5.png)

**Comment by willyelm** [comment]
Found the issue I got no time today to work on it but I'll have it fixed for the next couple of days, thank you for your help to make this compatible on windows environments

**Comment by willyelm** [comment]
working on this now I'll let you know as soon as I get it fixed.

**Comment by willyelm** [comment]
@AskYous any luck?

**Comment by AskYous** [comment]
@willyelm I'll have to wait until I get home because my current work account has no spaces. But I just updated the package and received the following error when launching. It worked before this update.

![image](https://cloud.githubusercontent.com/assets/791996/25098379/27f1def8-235d-11e7-98b2-27ad9ab4ed28.png)

**Comment by willyelm** [comment]
The issue is that you don't need to add the quotes in the binary path anymore where you have "C:\Program Files\node\node.exe" can be simply: C:\Program Files\node\node.exe, I will make it work both ways but in meantime please try that.

**Comment by AskYous** [comment]
@willyelm Cool that worked. I'll have to wait until I get home to check whether it works on my windows account that has spaces.

**Comment by AskYous** [comment]
@willyelm it worked!

**Comment by willyelm** [comment]
cool
