### ISSUE TITLE
Interested in the debugger namespace?

### ISSUE THREAD

**Issue by steelbrain** [willyelm/xatom-debug#9]
Hi @willyelm 

I currently own https://github.com/AtomDebugger (with a friend) as well as the `debugger` name on APM (https://atom.io/packages/debugger)

`atom-bugs` is not as predictable, so I would like to offer you the debugger name if you want, You have a pretty nice package and we are not using the name for anything working anyway.

**Comment by willyelm** [comment]
Hey @steelbrain, Thank you! yeah would love to have it let me know how we can coordinate the transfer

**Comment by steelbrain** [comment]
Hi @willyelm 

I'm @steelbrain on AtomIO Slack. Let's move this discussion there
